version: "3.7"
services:
  workspace:
    build: .
    image: map_builder_service:latest
    user: "${DOCKER_UID}:${DOCKER_GID}"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu, utility, compute]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIE=all
    shm_size: '14gb'
    volumes:
      - ./:/source
      # timeexit
      - /etc/localtime:/etc/localtime:ro
