# Model config (Pytorch Lightning)
seed_everything: 564
trainer:
  callbacks:
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: "val/loss"
        patience: 10
        verbose: True
        mode: "min"
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        dirpath: "results/checkpoints"
        monitor: "val/loss"
        filename: "best-checkpoint"
        save_top_k: 1
        mode: "min"
        verbose: True
  logger:
    - class_path: lightning.pytorch.loggers.TensorBoardLogger
      init_args:
        save_dir: "results/tb-logs/"
        name: ""
        version: ""
    - class_path: dvclive.lightning.DVCLiveLogger
      init_args:
        resume: True
        dir: "results/dvclive"
  accelerator: "auto"
  devices: 1
  max_epochs: 2
model:
  class_path: map_builder_service.lanenet.LaneNet
  init_args:
    pretrained: true
    embeding_size: 8
data:
  data_dir: "data/proc/dataset"
  train_size: 0.8
  line_radius: 10.0
  batch_size: 8
  image_size:
    - 288
    - 512
ckpt_path: null
